# Generated by Django 3.2 on 2022-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dyg53cwvw/image/upload/v1650379514/user-image_ds1u1v.jpg', upload_to='images/'),
        ),
    ]
