# Generated by Django 3.2 on 2022-04-20 09:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dyg53cwvw/image/upload/v1650379514/user-image_ds1u1v.jpg', max_length=255, verbose_name='image'),
        ),
    ]
