# Generated by Django 3.2 on 2022-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../user-image_ds1u1v.jpg', upload_to='images/'),
        ),
    ]
